language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
# Run tests in the browser
# before_install:
#     - export DISPLAY=:99.0
#     - sh -e /etc/init.d/xvfb start
before_script:
  - npm install testem -g
script:
  - testem ci
