language: node_js
node_js:
  - "node"

# Run tests in the browser
before_install:
  - export DISPLAY=:99.0
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - npm install -g testem

script:
  - phantomjs --version
  - testem launchers
  - testem ci
